name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        runners: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runners }}
    steps:
    - name: Prepare
      run: |
        runner=${{ matrix.runners }}
        ARCH=$(echo "$RUNNER" | grep -qE "-arm$" && echo "arm64" || echo "-amd64")
        echo "$ARCH"
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DockerhubUser }}
        password: ${{ secrets.DockerhubPass }}
    - uses: actions/checkout@v4
    - name: Build the Docker image
    #  run: docker buildx build --pull --push -t synerynx/payscepowerbill:1.0.${{ github.run_number }} --platform linux/arm64,linux/amd64 -t synerynx/payscepowerbill:latest .
      run: docker build . --file Dockerfile --tag synerynx/payscepowerbill:1.0.${{ github.run_number }}-$ARCH --tag synerynx/payscepowerbill:latest-$ARCH
    - name: Push
      run: docker push synerynx/payscepowerbill:1.0.${{ github.run_number }}-$ARCH
    - name: Push latest
      run: docker push synerynx/payscepowerbill:latest-$ARCH
