name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - v*
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY_IMAGE: synerynx/payscepowerbill

jobs:
  build:
    strategy:
      matrix:
        runners: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runners }}
    steps:
    - name: Prepare
      run: |
        runner=${{ matrix.runners }}
        if [[ "$runner" == *"-arm" ]]; then
            echo "ARCH=arm64" >> $GITHUB_ENV
        else
            echo "ARCH=amd64" >> $GITHUB_ENV
        fi
        echo "$ARCH"
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY_IMAGE }}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DockerhubUser }}
        password: ${{ secrets.DockerhubPass }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
  
    - name: Build and push by digest
      id: build
      uses: docker/build-push-action@v6
      with:
        #platforms: ${{ matrix.platform }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ env.REGISTRY_IMAGE }}
        outputs: type=image,push-by-digest=true,name-canonical=true,push=true

    - name: Export digest
      run: |
        mkdir -p ${{ runner.temp }}/digests
        digest="${{ steps.build.outputs.digest }}"
        touch "${{ runner.temp }}/digests/${digest#sha256:}"

    - name: Upload digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ env.ARCH }}
        path: ${{ runner.temp }}/digests/*
        if-no-files-found: error
        retention-days: 1
    #- name: Build the Docker image
    #  run: docker buildx build --pull --push -t synerynx/payscepowerbill:1.0.${{ github.run_number }} --platform linux/arm64,linux/amd64 -t synerynx/payscepowerbill:latest .
    #  run: docker build . --file Dockerfile --tag synerynx/payscepowerbill:1.0.${{ github.run_number }}-${{env.ARCH}} --tag synerynx/payscepowerbill:latest-${{env.ARCH}}
    #- name: Push
    #  run: docker push synerynx/payscepowerbill:1.0.${{ github.run_number }}-${{env.ARCH}}
    #- name: Push latest
    #  run: docker push synerynx/payscepowerbill:latest-$ARCH
  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DockerhubUser }}
          password: ${{ secrets.DockerhubPass }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}